a=("abc","bb","jdhh","gcool",1,4,7,8,4,6,3,9,0,5)
print(a)
print(type(a))
print(len(a))
print(a[4])
print("gcool" in a)
print("gcool" not in a)
for i in a:
    print(i)
print (a[7])
print (a[5:9])
print (a[6:])
print (a[:7])
print (a[-9:-3])
print (a[-5:])
print (a[:-9])
b=("abb",999,"gokul",726,"ggg",52,"fff",13,"cool")
print(b)
c=b*3
print(c)
